// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-security-incidents.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_security_incidents_default = defineTool({
  name: "list_security_incidents",
  title: "List security incidents",
  description: "List recent security incidents from the RUCU platform, ordered by most recent. Optionally filter by severity or status.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max rows to return (1-100)."),
    severity: z.enum(["low", "medium", "high", "critical"]).optional().describe("Filter by severity level."),
    status: z.string().optional().describe("Filter by status, e.g. open, contained, resolved.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, severity, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("security_incidents").select("*").order("created_at", { ascending: false }).limit(limit);
    if (severity) q = q.eq("severity", severity);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { incidents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-threat-alerts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_threat_alerts_default = defineTool2({
  name: "list_threat_alerts",
  title: "List threat alerts",
  description: "List recent threat alerts detected by the SIEM, ordered by most recent.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20).describe("Max rows to return (1-100)."),
    severity: z2.enum(["low", "medium", "high", "critical"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, severity }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("threat_alerts").select("*").order("created_at", { ascending: false }).limit(limit);
    if (severity) q = q.eq("severity", severity);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-firewall-logs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_firewall_logs_default = defineTool3({
  name: "list_firewall_logs",
  title: "List firewall logs",
  description: "List recent firewall log entries. Optionally filter by source IP or action.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).default(50).describe("Max rows (1-200)."),
    source_ip: z3.string().optional().describe("Filter by source IP address."),
    action: z3.string().optional().describe("Filter by action, e.g. block, allow.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, source_ip, action }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("firewall_logs").select("*").order("created_at", { ascending: false }).limit(limit);
    if (source_ip) q = q.eq("source_ip", source_ip);
    if (action) q = q.eq("action", action);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blocked-ips.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blocked_ips_default = defineTool4({
  name: "list_blocked_ips",
  title: "List blocked IPs",
  description: "List IP addresses currently blocked by the RUCU firewall.",
  inputSchema: {
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("blocked_ips").select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { blocked: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/block-ip.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var block_ip_default = defineTool5({
  name: "block_ip",
  title: "Block an IP address",
  description: "Add an IP address to the firewall block list. Default expiry is 24 hours; pass is_permanent=true for an indefinite block.",
  inputSchema: {
    ip_address: z5.string().min(3).describe("IPv4 or IPv6 address to block."),
    reason: z5.string().optional().describe("Human-readable reason for the block."),
    is_permanent: z5.boolean().default(false).describe("If true, the block does not expire."),
    hours: z5.number().int().min(1).max(720).default(24).describe("Hours to block for when not permanent.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ ip_address, reason, is_permanent, hours }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const expires_at = is_permanent ? null : new Date(Date.now() + hours * 3600 * 1e3).toISOString();
    const { data, error } = await supabaseForUser5(ctx).from("blocked_ips").insert({
      ip_address,
      reason: reason ?? "Blocked via MCP",
      is_permanent,
      expires_at,
      blocked_by: ctx.getUserId()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Blocked ${ip_address}` }],
      structuredContent: { blocked: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "usfotvrvfwugruyfxubf";
var mcp_default = defineMcp({
  name: "rucu-cybersecurity-mcp",
  title: "RUCU Cybersecurity MCP",
  version: "0.1.0",
  instructions: "Tools for the RUCU Unified Cyber Security platform. Read recent security incidents, threat alerts, firewall logs, and blocked IPs, or block an offending IP address. All tools act on behalf of the signed-in RUCU user under RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_security_incidents_default, list_threat_alerts_default, list_firewall_logs_default, list_blocked_ips_default, block_ip_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
